kind: Service
apiVersion: v1
metadata:
  name: cadvisor
  namespace: openfaas
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '10000'
spec:
  selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: cadvisor
  ports:
  - name: cadvisor
    protocol: TCP
    port: 10000
    targetPort: 10000
